bananhhao/Controllers/QLHoaDonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bananhhao.Models;

namespace bananhhao.Controllers
{
    public class QLHoaDonController : Controller
    {
        private DataClasses1DataContext db;
        public QLHoaDonController()
        {
            db = new DataClasses1DataContext();
        }
        // GET: QLHoaDon
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult LapHoaDon(string makh,int diennangtieuthu,double tiendien,int chisocuoi,string mahd)
        {
            int mess = db.laphoadon(diennangtieuthu, tiendien, makh, mahd, chisocuoi);
            if (mess == 1)
            {
                Session["ThongBao"] = "Trùng mã hoá đơn";
            }
            else
                Session["ThongBao"] = "001";
            return RedirectToAction("Index","QLTinhTienDien");
        }
    }
}

bananhhao/Controllers/QLTinhTienDienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bananhhao.Models;
namespace bananhhao.Controllers
{
    public class QLTinhTienDienController : Controller
    {
        // GET: QLTinhTienDien
        private DataClasses1DataContext db;
        public QLTinhTienDienController()
        {
            db = new DataClasses1DataContext();
        }
        public ActionResult Index()
        {
            List<khachhang> lst = db.khachhangs.ToList();
            return View(lst);
        }
        [HttpPost]
        public ActionResult TinhTien(string makh,int chisocuoi)
        {
            double diennangtieuthu = db.TinhDienNangTieuThu(chisocuoi);
            double tongsotien = tinhtiendien(chisocuoi);

            ViewBag.diennangtieuthu = diennangtieuthu;
            ViewBag.tongsotien = tongsotien * 1000;
            ViewBag.makh = makh;
            ViewBag.chisocuoi = chisocuoi;
            return View();


        }
        public double tinhtiendien(double sokwh)
        {
            Double sotien;
            if (sokwh < 0)
            {
                return 0;
            }
            else
            {
                if (sokwh > 0 && sokwh <= 100)
                {
                    sotien = sokwh * 1.242;
                }
                else if (sokwh > 100 && sokwh <= 150)
                {
                    sotien = 100 * 1.242 + (sokwh - 100) * 1.304;
                }
                else if (sokwh > 150 && sokwh <= 200)
                {
                    sotien = 100 * 1.242 + (150 - 100) * 1.304 + (200 - 150) * 1.651;
                }
                else if (sokwh > 200 && sokwh <= 300)
                {
                    sotien = 100 * 1.242 + (150 - 100) * 1.304 + (200 - 150) * 1.651 + (300 - 200) * 1.788;
                }
                else if (sokwh > 300 && sokwh <= 400)
                {
                    sotien = 100 * 1.242 + (150 - 100) * 1.304 + (200 - 150) * 1.651 + (300 - 200) * 1.788 + (400 - 300) * 1.912;
                }
                else
                {
                    sotien = 100 * 1.242 + (150 - 100) * 1.304 + (200 - 150) * 1.651 + (300 - 200) * 1.788 + (400 - 300) * 1.912 + (sokwh - 400) * 1.962;
                }
            }
            return sotien;

        }
    }
}

bananhhao/Views/QLTinhTienDien/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using bananhhao.Models;
@model List<khachhang>

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Tính tiền điện</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Danh sách khách hàng
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body ">
                @using (Html.BeginForm("TinhTien", "QLTinhTienDien",FormMethod.Post))
                {
                    <label>Mã khách hàng</label><input type="text" name="makh" /><label>Chỉ số cuối</label><input type="number" name="chisocuoi" />
                    <button type="submit">Tính tiền điện</button>
                }

                <table id="khachhang" width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                    <thead>
                        <tr>
                            <th>Mã Khách Hàng</th>
                            <th>Tên Khách hàng</th>
                            <th>Địa Chỉ</th>
                            <th>Điện Thoại</th>
                            <th>CMND</th>

                            <th>
                                <a href="#">Xóa</a> -
                                <a href="suakhachhang.html">Sửa</a>
                            </th>
                        </tr>
                        @foreach (khachhang kh in Model)
                        {
                            <tr>
                                <td class="tdNumber">@kh.makh</td>
                                <td class="tdCharacter">@kh.tenkh</td>
                                <td class="tdCharacter">@kh.diachi</td>
                                <td class="tdNumber">@kh.dt</td>
                                <td class="tdNumber">@kh.cmnd</td>

                            </tr>
                        }
                    </thead>
                    <tbody></tbody>
                </table>
                <!-- /.table-responsive -->
            </div>
            <!-- /.panel-body -->
        </div>
        <!-- /.panel -->
    </div>
    <!-- /.col-lg-12 -->
</div>

bananhhao/Views/QLTinhTienDien/TinhTien.cshtml
@{
    ViewBag.Title = "TinhTien";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table id="khachhang" width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
    <thead>
        <tr>
            <th>Mã hoá đơn</th>
            <th>Mã Khách Hàng</th>
            <th>Điện năng tiêu thụ</th>
            <th>Tổng tiền</th>



        </tr>
        @using (Html.BeginForm("LapHoaDon", "QLHoaDon", FormMethod.Post))
        {

            <tr>
                <td>
                    <label>Mã hoá đơn</label><input type="text" name="mahd" />
                </td>
                <td>
                    <label>@ViewBag.makh</label><input type="text" value="@ViewBag.makh" name="makh" hidden="hidden" />
                </td>
                <td>
                    <label>@ViewBag.diennangtieuthu</label><input type="text" value="@ViewBag.diennangtieuthu" name="diennangtieuthu" hidden="hidden" />
                </td>
                <td>
                    <label>@ViewBag.tongsotien</label><input type="text" value="@ViewBag.tongsotien" name="tiendien" hidden="hidden" />
                    <input type="text" value="@ViewBag.chisocuoi" name="chisocuoi" hidden="hidden" />
                </td>
                <td><button type="submit" class="btn btn-primary">Lập hoá đơn</button></td>
            </tr>
            
        }


    </thead>
    <tbody></tbody>
</table>