bananhhao/Controllers/QLDienKeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bananhhao.Models;
namespace bananhhao.Controllers
{
    public class QLDienKeController : Controller
    {
        private DataClasses1DataContext db;
        public QLDienKeController()
        {
            db = new DataClasses1DataContext();
        }
        // GET: QLDienKe
        public ActionResult Index()
        {
            List<dienke> lst = db.dienkes.ToList( );
            return View(lst);
        }
        [HttpGet]
        public ActionResult Insert()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult Insert(dienke dk)
        {
            if (db.dienkes.SingleOrDefault(x => x.madk == dk.madk) != null)
            {
                Session["ThongBao"] = "Mã điện kế đã tồn tại";
                return View("Insert");
            }
            else if (dk.madk.Length != 8 || dk.makh.Length == 0 || dk.ngaysx > DateTime.Now || dk.ngaylap > DateTime.Now || dk.ngaysx >= dk.ngaylap || dk.mota == null)
            {
                Session["ThongBao"] = "Thông tin nhập ko hợp lệ!";
                return View("Insert");
            }
            else
            {
                try
                {
                    db.dienkes.InsertOnSubmit(dk);
                    db.SubmitChanges();
                    Session["ThongBao"] = "001";
                }
                catch(Exception e)
                {
                    Session["ThongBao"] = e.Message;
                    return View("Insert");
                }
                return RedirectToAction("Index");
            }
          
        }
        [HttpGet]
        public ActionResult Edit(string id)
        {
            dienke dk = db.dienkes.SingleOrDefault(x => x.madk == id);
            return View(dk);
        }
    
        public ActionResult Delete(string madk)
        {
            try
            {
                db.dienkes.DeleteOnSubmit(db.dienkes.SingleOrDefault(x => x.madk == madk));
                db.SubmitChanges();
                return RedirectToAction("Index"); 
            }catch(Exception e)
            {
                Session["ThongBao"] = e.Message;
                return RedirectToAction("Index");
            }
          
            
        }
        [HttpPost]
        public ActionResult Edit(dienke dk)
        {
            if (db.dienkes.SingleOrDefault(x => x.madk == dk.madk) != null)
            {
                if (dk.madk.Length != 8 || dk.makh.Length == 0 || dk.ngaysx > DateTime.Now || dk.ngaylap > DateTime.Now || dk.ngaysx >= dk.ngaylap || dk.mota == null)
                {
                    Session["ThongBao"] = "Thông tin nhập ko hợp lệ!";
                    return RedirectToAction("Edit", new { id = dk.madk });
                }
                else
                {
                    try
                    {
                        dienke core = db.dienkes.SingleOrDefault(x => x.madk == dk.madk);
                        core.makh = dk.makh;
                        core.mota = dk.mota;
                        core.ngaylap = dk.ngaylap;
                        core.ngaysx = dk.ngaysx;
                        core.trangthai = dk.trangthai;
                        db.SubmitChanges();
                        Session["ThongBao"] = "002";
                    }
                    catch (Exception e)
                    {
                        Session["ThongBao"] = e.Message;
                        return RedirectToAction("Edit", new { id = dk.madk });
                    }
                    return RedirectToAction("Index");
                }
            }
            else
                return RedirectToAction("Index");


        }
    }
}

bananhhao/Controllers/QLGiaDienController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bananhhao.Models;
namespace bananhhao.Controllers
{
    public class QLGiaDienController : Controller
    {
        private DataClasses1DataContext db;
        // GET: QLGiaDien
        public QLGiaDienController()
        {
            db = new DataClasses1DataContext();
        }
        public ActionResult Index()
        {
             List<giadien>lst =db.giadiens.ToList();
            return View(lst);
        }
        [HttpGet]
        public ActionResult Insert()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Insert(giadien gd)
        {
            if (db.giadiens.SingleOrDefault(x => x.mabac == gd.mabac) !=null)
            {
                Session["ThongBao"] = "Mã bậc đã tồn tại";
                return View("Insert");
            }
            //else if (dk.madk.Length != 8 || dk.makh.Length == 0 || dk.ngaysx > DateTime.Now || dk.ngaylap > DateTime.Now || dk.ngaysx >= dk.ngaylap || dk.mota == null)
            //{
              //  Session["ThongBao"] = "Thông tin nhập ko hợp lệ!";
                //return View("Insert");
            //}
            else
            {
                try
                {
                    db.giadiens.InsertOnSubmit(gd);
                    db.SubmitChanges();
                    Session["ThongBao"] = "001";
                }
                catch (Exception e)
                {
                    Session["ThongBao"] = e.Message;
                    return View("Insert");
                }
                return RedirectToAction("Index");
            }

        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            giadien kh = db.giadiens.SingleOrDefault(x => x.mabac == id);
            return View(kh);
        }
        [HttpPost]
        public ActionResult Edit(int mabac, string tenbac, int tusokw, int densokw, decimal dongia,DateTime ngayapdung)
        {
            giadien save = new giadien { mabac = mabac, tenbac = tenbac, tusokw = tusokw, densokw = densokw, dongia = dongia, ngayapdung=ngayapdung };
            giadien check = db.giadiens.SingleOrDefault(x => x.mabac == mabac);
            try
            {

                if (mabac == 0 || tenbac == null || tusokw == 0 || densokw == 0|| dongia == 0 && ngayapdung==null)
                {
                    Session["ThongBao"] = "Có lỗi khi sửa giá điện";
                    return RedirectToAction("Edit", new { id = mabac });
                }
                /*else if (check != null)
                {
                    Session["ThongBao"] = "Số chứng minh đã tồn tại!";
                    return RedirectToAction("Edit", new { id = makh });
                }*/
                giadien kh = db.giadiens.SingleOrDefault(x => x.mabac == mabac);

                kh.tenbac = tenbac;
                kh.tusokw = tusokw;
                kh.densokw = densokw;
                kh.dongia = dongia;
                kh.ngayapdung = ngayapdung;
                db.SubmitChanges();
                Session["ThongBao"] = "002";
            }
            catch (Exception e)
            {
                Session["ThongBao"] = e.Message;
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(int mabac)
        {
            try
            {
                giadien kh = db.giadiens.SingleOrDefault(x => x.mabac == mabac);

                db.giadiens.DeleteOnSubmit(kh);
                db.SubmitChanges();
                Session["ThongBao"] = "003";
            }
            catch (Exception e)
            {
                Session["ThongBao"] = e.Message;
            }



            return RedirectToAction("Index");
        }
    }
}

bananhhao/Controllers/QLKhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bananhhao.Models;
namespace bananhhao.Controllers
{
    public class QLKhachHangController : Controller
    {

        // GET: QLKhachHang
        private DataClasses1DataContext db;
        public QLKhachHangController()
        {
            db = new DataClasses1DataContext();
        }
        public ActionResult Index()
        {
            List<khachhang> lst = db.khachhangs.ToList();

            return View(lst);
        }
        [HttpGet]
        public ActionResult Insert()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Insert(khachhang kh)
        {
            
            if(db.khachhangs.SingleOrDefault(x=>x.makh == kh.makh)!=null)
            {
                Session["ThongBao"] = "Mã khách hàng đã tồn tại!";
                return View("Insert");
            }
            else if(db.khachhangs.SingleOrDefault(x=>x.makh!=kh.makh && x.cmnd == kh.cmnd)!=null)
            {
                Session["ThongBao"] = "Số chứng minh đã tồn tại!";
                return View("Insert");
            }
            else if (kh.makh.Length < 13 || kh.tenkh == null || kh.diachi == null || kh.dt == null || kh.cmnd == null || kh.cmnd.Length != 9)
            {
                Session["ThongBao"] = "Có lỗi khi thêm khách hàng";
                return View("Insert");
            }
            else 
            {
                try
                {
                    db.khachhangs.InsertOnSubmit(kh);
                    db.SubmitChanges();
                    Session["ThongBao"] = "001";
                }
                catch (Exception e)
                {
                    Session["ThongBao"] = e.Message;
                    return View("Insert");
                }

            }
           
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(string id)
        {
            khachhang kh = db.khachhangs.SingleOrDefault(x => x.makh == id);
            return View(kh);
        }
        [HttpPost]
        public ActionResult Edit(string makh, string tenkh, string diachi, string dienthoai, string cmnd)
        {
            khachhang save = new khachhang { makh = makh, tenkh = tenkh, diachi = diachi, dt = dienthoai, cmnd = cmnd };
            khachhang check = db.khachhangs.SingleOrDefault(x => x.cmnd == cmnd && x.makh != makh);
            try
            {
               
                if (makh.Length < 13 || tenkh == null || diachi == null || dienthoai == null || cmnd.Length == 0 || cmnd.Length != 9)
                {
                    Session["ThongBao"] = "Có lỗi khi sửa khách hàng";
                    return RedirectToAction("Edit", new { id = makh });
                }
                else if(check!=null)
                {
                    Session["ThongBao"] = "Số chứng minh đã tồn tại!";
                    return RedirectToAction("Edit", new { id = makh });
                }
                khachhang kh = db.khachhangs.SingleOrDefault(x => x.makh == makh);
                
                kh.tenkh = tenkh;
                kh.diachi = diachi;
                kh.dt = dienthoai;
                kh.cmnd = cmnd;

                db.SubmitChanges();
                Session["ThongBao"] = "002";
            }
            catch (Exception e)
            {
                Session["ThongBao"] = e.Message;
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Delete(string makh)
        {
            try
            {
                khachhang kh = db.khachhangs.SingleOrDefault(x => x.makh == makh);

                db.khachhangs.DeleteOnSubmit(kh);
                db.SubmitChanges();
                Session["ThongBao"] = "003";
            }
            catch (Exception e)
            {
                Session["ThongBao"] = e.Message;
            }



            return RedirectToAction("Index");
        }
       
        
    }
}

bananhhao/Controllers/TraCuuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using bananhhao.Models;
namespace bananhhao.Controllers
{
    public class TraCuuController : Controller
    {
        private DataClasses1DataContext db;
        public TraCuuController()
        {
            db = new DataClasses1DataContext();
        }
        // GET: TraCuu
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult TimKiemKhachHang()
        {
            //;var kq = db.khachhangs.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult TimKiemKhachHang(string makh)
        {
            var result = db.khachhangs.Count(x => x.makh == makh);
            if (result > 0)
            {
                var kq = db.khachhangs.SingleOrDefault(x => x.makh == makh);
                return RedirectToAction("TimKiemKH", "Timkiem", new { @khachhang = kq.makh });
            }    
            else
            {
                Session["ThongBao"] = "Không có nhân viên nào trong đây!";
                return View();
            }    
                
            
        }
        [HttpGet]
        public ActionResult TraCuuDienKe()
        {
            //var kq = db.dienkes.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult TraCuuDienKe(string madk)
        {
            var result = db.dienkes.Count(x => x.madk == madk);
            if (result > 0)
            {
                var kq = db.dienkes.SingleOrDefault(x => x.madk == madk);
                return RedirectToAction("TimKiemDK", "Timkiem", new { @dienke = kq.madk });
            }
            else
            {
                Session["ThongBao"] = "Không có nhân viên nào trong đây!";
                return View();
            }
        }
    }
}

bananhhao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Quản lý tính tiền điện sinh hoạt</title>
    <link href="~/jquery-ui-1.12.1.custom/jquery-ui.min.css" rel="stylesheet" />
    <!-- Bootstrap Core CSS -->
    <link href="/Assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/Assets/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="/Assets/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="/Assets/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/Assets/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/Assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    @*custom css*@
    <style>
        .tdNumber {
            text-align: center;
            vertical-align: middle;
        }

        .tdCharacter {
            text-align: left;
            vertical-align: middle;
        }
        th {
            text-align: center;
            vertical-align: middle;
        }
    </style>

</head>

<body>


    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html">Đề tài thực tập tốt nghiệp</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
          
            </ul>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-bar-chart-o fa-fw"></i> Khách Hàng
                                <span class="fa arrow"></span>
                            </a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Index","QLKhachHang")">Danh Sách</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Insert","QLKhachHang")">Thêm Khách Hàng</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-bar-chart-o fa-fw"></i> Điện Kế
                                <span class="fa arrow"></span>
                            </a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Index","QLDienKe")">Danh Sách</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Insert","QLDienKe")">Thêm Điện Kế</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                       
                        <li>
                            <a href="#">
                                <i class="fa fa-bar-chart-o fa-fw"></i>Giá Điện
                                <span class="fa arrow"></span>
                            </a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Index","QLGiaDien")">Danh Sách</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Insert","QLGiaDien")">Thêm Điện Kế</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-bar-chart-o fa-fw"></i> Tra Cứu Thông tin
                                <span class="fa arrow"></span>
                            </a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("TimKiemKhachHang","TraCuu")">Tìm Kiếm Khách Hàng</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("TraCuuDienKe","TraCuu")">Tìm Kiếm Điện kế</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="@Url.Action("Index","QLTinhTienDien")">
                                QL Tính tiền điện
                            </a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        <div id="page-wrapper">
            <div class="row">
                @if (Session["ThongBao"] != null)
            {
                if (Session["ThongBao"].ToString() == "001")
                {
                    <div class="alert alert-success">Thêm thành công</div>

                Session["ThongBao"] = null;
            }
            else if (Session["ThongBao"].ToString() == "002")
            {
                <div class="alert alert-success">Sửa thành công</div>

            Session["ThongBao"] = null;
        }
        else if (Session["ThongBao"].ToString() == "003")
        {
            <div class="alert alert-success">Xoá thành công</div>

        Session["ThongBao"] = null;
    }
    else
    {
        <div class="alert alert-danger">@Session["ThongBao"]</div>

    Session["ThongBao"] = null;
}
}
                @RenderBody()

                <!-- /.row -->
                <!-- /.row -->
                <!-- /.row -->
                <!-- /.row -->
            </div>
            <!-- /#page-wrapper -->

        </div>
        <!-- /#wrapper -->
        <!-- jQuery -->
        <script src="/Assets/vendor/jquery/jquery.min.js"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="/Assets/vendor/bootstrap/js/bootstrap.min.js"></script>

        <!-- Metis Menu Plugin JavaScript -->
        <script src="/Assets/vendor/metisMenu/metisMenu.min.js"></script>

        <!-- DataTables JavaScript -->
        <script src="/Assets/vendor/datatables/js/jquery.dataTables.min.js"></script>
        <script src="/Assets/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
        <script src="/Assets/vendor/datatables-responsive/dataTables.responsive.js"></script>

        <!-- Custom Theme JavaScript -->
        <script src="/Assets/dist/js/sb-admin-2.js"></script>

        <!-- Page-Level Demo Scripts - Tables - Use for reference -->
        <script>
            $(document).ready(function () {
                $('#dataTables-example').DataTable({
                    responsive: true
                });

            });
            $('.nhapso').keydown(function (event) {
                if (event.keyCode == 46 || event.keyCode == 8 || event.keyCode == 9) {

                }
                else {

                    if ((event.keyCode < 48 || event.keyCode > 57) && (event.keyCode < 96 || event.keyCode > 105)) {
                        event.preventDefault();

                    }
                }
            });
            
        </script>
       @RenderSection("scripts",required:false)
</body>

</html>